"""
systems/synthetic.py
====================
file generated by claude sonnet 4.6 extended, and is a temporary file for demonstrative testing purposes
Source:
    Planet spacing distribution: Pu & Wu 2015
        - Adjacent planets separated by 3-8 mutual Hill radii
    Planet mass distribution: Fabrycky et al. 2012
        - 1-20 Earth masses, log-uniform
    Innermost planet semi-major axis: 0.05-0.15 AU uniform
"""

import numpy as np
from systems.base import BaseSystem
from core.constants import M_EARTH


N_PLANETS    = 3     # always 3 inner planets
STAR_MASS    = 1.0   # Msun

A_MIN        = 0.05  # AU — innermost planet minimum
A_MAX        = 0.15  # AU — innermost planet maximum

M_PLANET_MIN = 1.0   # Earth masses
M_PLANET_MAX = 20.0  # Earth masses

K_MIN        = 3.5   # mutual Hill radii minimum spacing (Pu & Wu 2015)
K_MAX        = 8.0   # mutual Hill radii maximum spacing


class SyntheticTestingSystem(BaseSystem):
    name      = "synthetic"
    star_mass = STAR_MASS

    def __init__(self, seed: int, outer_giant: dict | None = None):
        super().__init__(seed=seed, outer_giant=outer_giant)
        self.planets = self._generate_planets()

    def _generate_planets(self) -> list:
        masses_msun = np.exp(
            self._rng.uniform(np.log(M_PLANET_MIN), np.log(M_PLANET_MAX), size=N_PLANETS)
        ) * M_EARTH

        planets = []
        a_i = float(self._rng.uniform(A_MIN, A_MAX))

        for i in range(N_PLANETS):
            if i > 0:
                K      = float(self._rng.uniform(K_MIN, K_MAX))
                a_i, _ = _place_next_planet(
                    a_prev=planets[i - 1]["a"],
                    m_prev=masses_msun[i - 1],
                    m_curr=masses_msun[i],
                    K=K,
                    M_star=STAR_MASS,
                )

            planets.append({
                "name": f"p{i + 1}",
                "m":    float(masses_msun[i]),
                "a":    float(a_i),
            })

        return planets


def _mutual_hill_radius(a_i: float, a_j: float, m_i: float, m_j: float, M_star: float) -> float:
    """
    R_mH = ((a_i + a_j) / 2) * ((m_i + m_j) / (3 * M_star))^(1/3)

    Note: a_avg is outside the cube root.
    """
    return ((a_i + a_j) / 2.0) * ((m_i + m_j) / (3.0 * M_star)) ** (1.0 / 3.0)


def _place_next_planet(a_prev: float, m_prev: float, m_curr: float,
                       K: float, M_star: float, n_iter: int = 3) -> tuple[float, float]:
    """
    Iteratively solve for a_i = a_prev + K * R_mH(a_prev, a_i).

    Converges in 2-3 iterations for super-Earth masses around solar-type stars.

    Returns:
        a_i  : converged semi-major axis (AU)
        R_mH : converged mutual Hill radius (AU)
    """
    a_i  = a_prev
    R_mH = 0.0

    for _ in range(n_iter):
        R_mH = _mutual_hill_radius(a_prev, a_i, m_prev, m_curr, M_star)
        a_i  = a_prev + K * R_mH

    return a_i, R_mH